fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.13.1
    mailalias_core:
      repo: https://github.com/puppetlabs/puppetlabs-mailalias_core.git
      ref: 1.0.5
      puppet_version: ">= 6.0.0"
    sshkeys_core:
      repo: https://github.com/puppetlabs/puppetlabs-sshkeys_core.git
      ref: 1.0.2
      puppet_version: ">= 6.0.0"
  symlinks:
    root: "#{source_dir}"
