fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    mailalias_core:
      repo: puppetlabs/mailalias_core
    sshkeys_core:
      repo: puppetlabs/sshkeys_core
  symlinks:
    root: "#{source_dir}"
