---
.travis.yml:
  deploy: false
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-6
      collection: puppet5
    - set: centos-6
      collection: puppet6
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/spec_helper_acceptance.rb:
  puppet_collection_modules:
    - collection: puppet6
      modules:
      - puppetlabs-mailalias_core
      - puppetlabs-sshkeys_core
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
