language: ruby
sudo: false
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: "bundle exec rake test"
matrix:
  fast_finish: true
  include:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 1.7"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 1.7"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 4.0" FACTER_GEM_VERSION="~> 2.0"
    - rvm: 2.1.5
      sudo: required
      services: docker
      env: BEAKER_set="centos-6-x64-docker"
      bundler_args:
      script: sudo service docker restart ; sleep 10 ; bundle exec rake beaker
    - rvm: 2.1.5
      sudo: required
      services: docker
      env: BEAKER_set="centos-7-x64-docker"
      bundler_args:
      script: sudo service docker restart ; sleep 10 ; bundle exec rake beaker
notifications:
  email: false
